name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile plugin
        run: ./build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: compiled-plugin
          path: build/lan_of_doom_map_settings.smx

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          TARGET_FOLDER: releases/nightly